/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2021-02-26 08:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.data;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#map {\r\n");
      out.write("\tposition:absolute;  width:800px; height:600px;\r\n");
      out.write("\tleft:50%; top:50%; transform:translate(-50%, -50%) ;\r\n");
      out.write("\tborder:2px solid #666; display:none;\r\n");
      out.write("}\r\n");
      out.write(".page_next { background:url('imgs/page_next.jpg') center no-repeat; }\r\n");
      out.write(".page_last { background:url('imgs/page_last.jpg') center no-repeat;}\r\n");
      out.write(".page_first { background:url('imgs/page_first.jpg') center no-repeat;}\r\n");
      out.write(".page_prev { background:url('imgs/page_prev.jpg') center no-repeat;}\r\n");
      out.write("\r\n");
      out.write(".marker { font-weight:bold; }\r\n");
      out.write("\r\n");
      out.write(".list-view, .grid-view { font-size:25px; color:#3367d6; \r\n");
      out.write("\tpadding-top:3px; padding-left:5px }\r\n");
      out.write("\t\r\n");
      out.write("#data-list .pharmacy li div:first-child { height:25px; }\r\n");
      out.write("#data-list .pharmacy li div:last-child { font-size:14px;}\r\n");
      out.write("table.animal img { width:100px; height:100px; }\r\n");
      out.write("\r\n");
      out.write("ul.animal img { width:100%; height:100%; } \r\n");
      out.write("ul.animal li div.li-top { height:65% }\r\n");
      out.write("ul.animal li div.li-top > div { float:left; padding:0; height:100%; }\r\n");
      out.write("ul.animal li div.li-top > div:first-child { width:40%; }\r\n");
      out.write("ul.animal li > div:nth-child(2) { font-size:14px }\r\n");
      out.write(".spec { width:60%; }\r\n");
      out.write(".spec div { height:25% !important; padding:0 0 0 10px !important; }\r\n");
      out.write(".spec div:nth-child(3) {  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>공공데이터</h3>\r\n");
      out.write("<div class='btnSet dataOption'>\r\n");
      out.write("\t<a class='btn-fill'>약국조회</a>\r\n");
      out.write("\t<a class='btn-empty'>유기동물조회</a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id='list-top'>\r\n");
      out.write("\t<ul class='common'>\r\n");
      out.write("\t\t<li><select id='pageList' class='w-px80'>\r\n");
      out.write("\t\t\t<option value='10'>10개씩</option>\r\n");
      out.write("\t\t\t<option value='20'>20개씩</option>\r\n");
      out.write("\t\t\t<option value='30'>30개씩</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class='list-view'>\r\n");
      out.write("\t\t\t<i class='fas fa-list' style='vertical-align:top;'></i></li>\r\n");
      out.write("\t\t<li class='grid-view'>\r\n");
      out.write("\t\t\t<i class='fas fa-th' style='vertical-align:top;'></i></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div style='margin:20px 0 auto' id='data-list'></div>\r\n");
      out.write("<div class='btnSet'>\r\n");
      out.write("\t<div class='page_list'></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id='popup-background'></div>\r\n");
      out.write("<div id='map'></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"loading\"><img src=\"imgs/loading.gif\"/></div>\r\n");
      out.write("<script\r\n");
      out.write("      src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCsrerDHJrp9Wu09Ij7MUELxCTPiYfxfBI\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("// pharmacy_list( 1 );\r\n");
      out.write("$(function(){\r\n");
      out.write(" \t$('.dataOption a:eq(1)').trigger('click');\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function pharmacy_list( page ){\r\n");
      out.write("\t$('.loading').css('display', 'block');\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/pharmacy',\r\n");
      out.write("\t\tdata: { pageNo:page, rows:pageList },\r\n");
      out.write("\t\tsuccess: function( response ){\r\n");
      out.write("\t\t\t$('.loading').css('display', 'none');\r\n");
      out.write("\t\t\tif( viewType=='list' ){\r\n");
      out.write("\t\t\t\tpharmacy_list_data( $(response.item), true );\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tpharmacy_grid_data( $(response.item), true );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmakePage( response.count, page );\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error: function(req, text){\r\n");
      out.write("\t\t\t$('.loading').css('display', 'none');\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function animal_sido(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/animal/sido',\r\n");
      out.write("\t\tsuccess: function(response){\r\n");
      out.write("\t\t\tvar tag \r\n");
      out.write("\t\t\t= '<ul class=\"animal-top\">'\r\n");
      out.write("\t\t\t\t+ '<li><select id=\"sido\" class=\"w-px120\">'\r\n");
      out.write("\t\t\t\t\t+ '<option value=\"\">시도 선택</option>';\r\n");
      out.write("\t\t\t$(response.item).each(function(){\r\n");
      out.write("\t\t\t\ttag += '<option value=\"'+ this.orgCd +'\">'+ this.orgdownNm +'</option>';\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\ttag += '</select></li></ul>';\r\n");
      out.write("\t\t\t$('#list-top').prepend(tag);\r\n");
      out.write("\t\t\tanimal_type();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error: function(req,text){\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//축종\r\n");
      out.write("function animal_type(){\r\n");
      out.write("\tvar tag \r\n");
      out.write("\t\t= '<li>'\r\n");
      out.write("\t\t+ '<select id=\"upkind\" class=\"w-px80\">'\r\n");
      out.write("\t\t+ '<option value=\"\">축종 선택</option>'\r\n");
      out.write("\t\t+ '<option value=\"417000\">개</option>'\r\n");
      out.write("\t\t+ '<option value=\"422400\">고양이</option>'\r\n");
      out.write("\t\t+ '<option value=\"429900\">기타</option>'\r\n");
      out.write("\t\t+ '</select> '\r\n");
      out.write("\t\t+ '</li>';\r\n");
      out.write("\t$('#sido').closest('li').after(tag);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//축종에 따른 품종 조회\r\n");
      out.write("function animal_kind(){\r\n");
      out.write("\t$('#kind').remove();\r\n");
      out.write("\tif( $('#upkind').val()=='' ) return;\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/animal/animal_kind',\r\n");
      out.write("\t\tdata: { upkind:$('#upkind').val() },\r\n");
      out.write("\t\tsuccess: function(response){\r\n");
      out.write("\t\t\tvar tag = '<li>'\r\n");
      out.write("\t\t\t\t+ '<select id=\"kind\" class=\"w-px200\">'\r\n");
      out.write("\t\t\t\t+ \"<option value=''>품종 선택</option>\";\r\n");
      out.write("\t\t\t\t$(response.item).each(function(){\r\n");
      out.write("\t\t\t\t\ttag += '<option value=\"'+ this.kindCd +'\">'+ this.KNm +'</option>';\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\ttag += '</select></li>';\r\n");
      out.write("\t\t\t$('#upkind').closest('li').after(tag);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error: function(req, text){\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//시도에 따른 시군구 조회\r\n");
      out.write("function animal_sigungu(){\r\n");
      out.write("\t$('#sigungu, #shelter').remove();\r\n");
      out.write("\tif( $('#sido').val()=='' ) return;\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/animal/sigungu',\r\n");
      out.write("\t\tdata: { sido:$('#sido').val() },\r\n");
      out.write("\t\tsuccess: function(response){\r\n");
      out.write("\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\tif( response.item.length>0 ){ //세종시의 경우 시군구가 없음\r\n");
      out.write("\t\t\t\tvar tag = '<li>'\r\n");
      out.write("\t\t\t\t\t+ '<select class=\"w-px120\" id=\"sigungu\">'\r\n");
      out.write("\t\t\t\t\t+ '<option value=\"\">시군구 선택</option>';\r\n");
      out.write("\t\t\t\t$(response.item).each(function(){\r\n");
      out.write("\t\t\t\t\ttag += '<option value=\"'+ this.orgCd +'\">'+ this.orgdownNm +'</option>';\t\t\t\t\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t\ttag += '</select></li>';\r\n");
      out.write("\t\t\t\t$('#sido').closest('li').after(tag);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},error: function(req, text){\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//시군구에 따른 보호소 조회\r\n");
      out.write("function animal_shelter(){\r\n");
      out.write("\t$('#shelter').remove();\r\n");
      out.write("\tif( $('#sigungu').length==0 || $('#sigungu').val()=='' ) return;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/animal/shelter',\r\n");
      out.write("\t\tdata: { sido:$('#sido').val(), sigungu:$(\"#sigungu\").val() },\r\n");
      out.write("\t\tsuccess: function( response ){\r\n");
      out.write("\t\t\tvar tag = '<li><select class=\"w-px200\" id=\"shelter\">'\r\n");
      out.write("\t\t\t\t+ '<option value=\"\">보호소 선택</option>';\r\n");
      out.write("\t\t\t$(response.item).each(function(){\r\n");
      out.write("\t\t\t\ttag += '<option value=\"'+ this.careRegNo +'\">'+ this.careNm +'</option>';\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\ttag += '</select></li>';\r\n");
      out.write("\t\t\t$('#sigungu').closest('li').after(tag);\r\n");
      out.write("\t\t},error: function(req, text){\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//유기동물목록 조회\r\n");
      out.write("function animal_list( pageNo ){\r\n");
      out.write("\tif( $('#sido').length==0 ) animal_sido(); \r\n");
      out.write("\t\r\n");
      out.write("\tvar animal = new Object();\r\n");
      out.write("\tanimal.pageNo = pageNo;\r\n");
      out.write("\tanimal.rows = $('#pageList').val();\r\n");
      out.write("\tanimal.sido = $('#sido').length>0 ? $('#sido').val() : \"\"; //시도\r\n");
      out.write("\tanimal.upkind = $('#upkind').length>0 ? $('#upkind').val() : \"\"; //축종:개,고양이,기타\r\n");
      out.write("\tanimal.kind = $('#kind').length>0 ? $('#kind').val() : \"\"; //품종\r\n");
      out.write("\tanimal.sigungu = $('#sigungu').length>0 ? $('#sigungu').val() : \"\";  //시군구\r\n");
      out.write("\tanimal.shelter = $('#shelter').length>0 ? $('#shelter').val() : \"\";  //보호소\r\n");
      out.write("\t\r\n");
      out.write("\t$('.loading').css('display', 'block');\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: 'data/animal/list',\r\n");
      out.write("\t\tdata: JSON.stringify(animal),\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\tcontentType: 'application/json',\r\n");
      out.write("\t\tsuccess: function( response ){\r\n");
      out.write("\t\t\tif( viewType=='list' )  animal_list_data( $(response.item), true );\r\n");
      out.write("\t\t\telse\t\t\t\t\tanimal_grid_data( $(response.item), true );\r\n");
      out.write("\t\t\tmakePage( response.count, pageNo );\r\n");
      out.write("\t\t\t$('.loading').css('display', 'none');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error: function(req, text){\r\n");
      out.write("\t\t\talert(text+':'+req.status);\r\n");
      out.write("\t\t\t$('.loading').css('display', 'none');\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function animal_list_data(data, type){\r\n");
      out.write("\tvar tag = '<table class=\"animal\">';\r\n");
      out.write("\tconsole.log( data.length )\r\n");
      out.write("\t\r\n");
      out.write("\tif( (type && data.length==0) \r\n");
      out.write("\t\t\t||  (!type && data.length==1 && $('.li-top').length==0) ){\r\n");
      out.write("\t\ttag += '<tr><td colspan=\"11\">해당 유기동물이 없습니다</td></tr>';\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\tif( type ){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\ttag += '<tr><td class=\"w-px100\" rowspan=\"3\"><img src=\"'+ this.filename +'\"/></td>'\r\n");
      out.write("\t\t+ '<th class=\"w-px80\">성별</th><td class=\"w-px60\">'+ this.sexCd +'</td>'\r\n");
      out.write("\t\t+ '<th class=\"w-px40\">나이</th><td class=\"w-px100\">'+ this.age +'</td>'\r\n");
      out.write("\t\t+ '<th class=\"w-px40\">체중</th><td class=\"w-px80\">'+ this.weight +'</td>'\r\n");
      out.write("\t\t+ '<th class=\"w-px40\">색상</th><td>'+ this.colorCd +'</td>'\r\n");
      out.write("\t\t+ '<th class=\"w-px60\">접수일자</th><td class=\"w-px100\">'+ this.happenDt +'</td>'\r\n");
      out.write("\t\t+ '</tr>';\r\n");
      out.write("\ttag += '<tr><th>특징</th><td colspan=\"9\" class=\"left\">'+ this.specialMark +'</td></tr>'\r\n");
      out.write("\t\t+ '<tr><th>발견장소</th><td colspan=\"8\" class=\"left\">'+ this.happenPlace +'</td>'\r\n");
      out.write("\t\t+ '<td>'+ this.processState +'</td>'\r\n");
      out.write("\t\t+ '</tr>';\r\n");
      out.write("\ttag += '<tr><td colspan=\"2\">'+ this.careNm +'</td>'\r\n");
      out.write("\t\t+ '<td colspan=\"7\" class=\"left\">'+ this.careAddr +'</td>'\r\n");
      out.write("\t\t+ '<td colspan=\"2\">'+ this.careTel +'</td>'\r\n");
      out.write("\t\t+ '</tr>';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\ttag += '<tr><td class=\"w-px100\" rowspan=\"3\"><img src=\"'+ $(this).data('filename') +'\"/></td>'\r\n");
      out.write("\t\t\t+ '<th class=\"w-px80\">성별</th><td class=\"w-px60\">'+ $(this).data('sexcd') +'</td>'\r\n");
      out.write("\t\t\t+ '<th class=\"w-px40\">나이</th><td class=\"w-px100\">'+ $(this).data('age') +'</td>'\r\n");
      out.write("\t\t\t+ '<th class=\"w-px40\">체중</th><td class=\"w-px80\">'+ $(this).data('weight') +'</td>'\r\n");
      out.write("\t\t\t+ '<th class=\"w-px40\">색상</th><td>'+ $(this).data('colorcd') +'</td>'\r\n");
      out.write("\t\t\t+ '<th class=\"w-px60\">접수일자</th><td class=\"w-px100\">'+ $(this).data('happendt') +'</td>'\r\n");
      out.write("\t\t\t+ '</tr>';\r\n");
      out.write("\t\ttag += '<tr><th>특징</th><td colspan=\"9\" class=\"left\">'+ $(this).data('specialmark') +'</td></tr>'\r\n");
      out.write("\t\t\t+ '<tr><th>발견장소</th><td colspan=\"8\" class=\"left\">'+ $(this).data('happenplace') +'</td>'\r\n");
      out.write("\t\t\t+ '<td>'+ $(this).data('processstate') +'</td>'\r\n");
      out.write("\t\t\t+ '</tr>';\r\n");
      out.write("\t\ttag += '<tr><td colspan=\"2\">'+ $(this).data('carenm') +'</td>'\r\n");
      out.write("\t\t\t+ '<td colspan=\"7\" class=\"left\">'+ $(this).data('careaddr') +'</td>'\r\n");
      out.write("\t\t\t+ '<td colspan=\"2\">'+ $(this).data('caretel') +'</td>'\r\n");
      out.write("\t\t\t+ '</tr>';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\ttag += '</table>';\r\n");
      out.write("\t$('#data-list').html(tag);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function animal_grid_data(data, type){\r\n");
      out.write("\tvar tag = '<ul class=\"animal grid\">';\r\n");
      out.write("\r\n");
      out.write("\tif( ( type && data.length==0 ) || (!type && data.length==1) ){\r\n");
      out.write("\t\ttag += '<li style=\"width:100%; height:32px !important\">해당 유기동물이 없습니다</li>';\r\n");
      out.write("\t}else{\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tif( type ){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\ttag += '<li data-filename=\"'+ this.filename + '\" '\r\n");
      out.write("\t\t\t + 'data-age=\"'+ this.age + '\" data-sexcd=\"' + this.sexCd + '\" ' \r\n");
      out.write("\t\t\t + 'data-weight=\"'+ this.weight + '\" data-colorcd=\"' + this.colorCd + '\" '\r\n");
      out.write("\t\t\t + 'data-processstate=\"'+ this.processState + '\" '\r\n");
      out.write("\t\t\t + 'data-carenm=\"'+ this.careNm + '\" '\r\n");
      out.write("\t\t\t + 'data-happendt=\"'+ this.happenDt + '\" '\r\n");
      out.write("\t\t\t + 'data-specialmark=\"'+ this.specialMark + '\" '\r\n");
      out.write("\t\t\t + 'data-happenplace=\"'+ this.happenPlace + '\" '\r\n");
      out.write("\t\t\t + 'data-careaddr=\"'+ this.careAddr + '\" '\r\n");
      out.write("\t\t\t + 'data-caretel=\"'+ this.careTel + '\" '\t\t\t\t\t \r\n");
      out.write("\t\t\t + '>'\r\n");
      out.write("\t\t\t+ '<div class=\"li-top\">'\r\n");
      out.write("\t\t\t\t+ '<div><img src=\"'+ this.filename +'\"/></div>'\r\n");
      out.write("\t\t\t\t+ '<div class=\"spec\">'\r\n");
      out.write("\t\t\t\t\t+ '<div><span>'+ this.age +'</span>'\r\n");
      out.write("\t\t\t\t\t\t + '<span style=\"float:right\">'+ this.sexCd +'</span></div>'\r\n");
      out.write("\t\t\t\t\t+ '<div>'+ this.weight +'</div>'\t \r\n");
      out.write("\t\t\t\t\t+ '<div>'+ this.colorCd +'</div>'\t \r\n");
      out.write("\t\t\t\t\t+ '<div>'+ this.processState +'</div>'\t \r\n");
      out.write("\t\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t+ '<div><span>'+ this.careNm +'</span>'\r\n");
      out.write("\t\t\t\t + '<span style=\"float:right\">'+ this.happenDt +'</span>'\r\n");
      out.write("\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t+ '</li>';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar datas;\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\tvar idx = $(this).index()%4;\r\n");
      out.write("\t\t\tif( idx==0 ){\r\n");
      out.write("\t\t\t\tdatas = {};\r\n");
      out.write("\t\t\t\tdatas.filename = $(this).find('img').attr('src');\r\n");
      out.write("\t\t\t\tdatas.age = $(this).children('td:eq(2)').text();\r\n");
      out.write("\t\t\t\tdatas.sexcd = $(this).children('td:eq(1)').text();\r\n");
      out.write("\t\t\t\tdatas.weight = $(this).children('td:eq(3)').text();\r\n");
      out.write("\t\t\t\tdatas.colorcd = $(this).children('td:eq(4)').text();\r\n");
      out.write("\t\t\t\tdatas.happendt = $(this).children('td:eq(5)').text();\r\n");
      out.write("\t\t\t}else if( idx==1 ){\r\n");
      out.write("\t\t\t\tdatas.specialmark = $(this).children('td:eq(0)').text();\r\n");
      out.write("\t\t\t}else if( idx==2 ){\r\n");
      out.write("\t\t\t\tdatas.processstate = $(this).children('td:eq(1)').text();\r\n");
      out.write("\t\t\t\tdatas.happenplace = $(this).children('td:eq(0)').text();\r\n");
      out.write("\t\t\t}else if( idx==3 ){\r\n");
      out.write("\t\t\t\tdatas.carenm = $(this).children('td:eq(0)').text();\r\n");
      out.write("\t\t\t\tdatas.careaddr = $(this).children('td:eq(1)').text();\r\n");
      out.write("\t\t\t\tdatas.caretel = $(this).children('td:eq(2)').text();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttag += '<li data-filename=\"'+ datas.filename + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-age=\"'+ datas.age + '\" data-sexcd=\"' + datas.sexcd + '\" ' \r\n");
      out.write("\t\t\t\t\t + 'data-weight=\"'+ datas.weight + '\" data-colorcd=\"' + datas.colorcd + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-processstate=\"'+ datas.processstate + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-carenm=\"'+ datas.carenm + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-happendt=\"'+ datas.happendt + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-specialmark=\"'+ datas.specialmark + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-happenplace=\"'+ datas.happenplace + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-careaddr=\"'+ datas.careaddr + '\" '\r\n");
      out.write("\t\t\t\t\t + 'data-caretel=\"'+ datas.caretel + '\" '\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t + '>'\r\n");
      out.write("\t\t\t\t\t+ '<div class=\"li-top\">'\r\n");
      out.write("\t\t\t\t\t\t+ '<div><img src=\"'+ datas.filename +'\"/></div>'\r\n");
      out.write("\t\t\t\t\t\t+ '<div class=\"spec\">'\r\n");
      out.write("\t\t\t\t\t\t\t+ '<div><span>'+ datas.age +'</span>'\r\n");
      out.write("\t\t\t\t\t\t\t\t + '<span style=\"float:right\">'+ datas.sexcd +'</span></div>'\r\n");
      out.write("\t\t\t\t\t\t\t+ '<div>'+ datas.weight +'</div>'\t \r\n");
      out.write("\t\t\t\t\t\t\t+ '<div>'+ datas.colorcd +'</div>'\t \r\n");
      out.write("\t\t\t\t\t\t\t+ '<div>'+ datas.processstate +'</div>'\t \r\n");
      out.write("\t\t\t\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t\t\t+ '<div><span>'+ datas.carenm +'</span>'\r\n");
      out.write("\t\t\t\t\t\t + '<span style=\"float:right\">'+ datas.happendt +'</span>'\r\n");
      out.write("\t\t\t\t\t+ '</div>'\r\n");
      out.write("\t\t\t\t\t+ '</li>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttag += '</ul>';\r\n");
      out.write("\t$('#data-list').html(tag);\r\n");
      out.write("\tvar len = $('.animal li').length;\r\n");
      out.write("\t$('#data-list .animal').css('height'\r\n");
      out.write("\t\t\t, ((len%5>0 ? 1 :0) + Math.floor(len/5)) \r\n");
      out.write("\t\t\t\t\t* $('.animal li').outerHeight(true) - 20 );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var pageList = 10, blockPage = 10;\r\n");
      out.write("function makePage(totalList, curPage){\r\n");
      out.write("\tvar page = pageVO(totalList, curPage);\r\n");
      out.write("\tvar tag='';\r\n");
      out.write("\r\n");
      out.write("\tif( page.curBlock > 1 ){\r\n");
      out.write("\t\ttag += '<a class=\"page_first\" data-page=\"1\">처음</a>'\r\n");
      out.write("\t\t\t+ '<a class=\"page_prev\" data-page=\"'\r\n");
      out.write("\t\t\t\t\t\t+ (page.beginPage-blockPage) +'\" >이전</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var no=page.beginPage; no<=page.endPage; no++){\r\n");
      out.write("\t\tif(no==curPage) tag += '<span class=\"page_on\">'+ no +'</span>';\r\n");
      out.write("\t\telse tag += '<a class=\"page_off\" data-page=\"'+ no +'\" >'+ no +'</a>'; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif( page.curBlock < page.totalBlock ){\r\n");
      out.write("\t\ttag += '<a class=\"page_next\" data-page=\"'+ (page.endPage+1) +'\">다음</a>'\r\n");
      out.write("\t\t\t+ '<a class=\"page_last\" data-page=\"'+ page.totalPage +'\">마지막</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$('.page_list').html(tag);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageVO(totalList, curPage){\r\n");
      out.write("\tvar page = new Object();\r\n");
      out.write("\tpage.totalPage = parseInt(totalList / pageList)\r\n");
      out.write("\t\t\t\t\t+  (totalList % pageList == 0 ? 0 : 1) ;\r\n");
      out.write("\tpage.totalBlock = parseInt(page.totalPage / blockPage)\r\n");
      out.write("\t                + (page.totalPage % blockPage==0 ? 0 : 1);\r\n");
      out.write("    page.curBlock = parseInt(curPage / blockPage)\r\n");
      out.write("    \t\t\t\t+ (curPage % blockPage==0 ? 0 : 1);\r\n");
      out.write("\tpage.endPage = page.curBlock * blockPage;\r\n");
      out.write("\tpage.beginPage = page.endPage - (blockPage-1);\r\n");
      out.write("\tif( page.endPage > page.totalPage )  page.endPage = page.totalPage;\r\n");
      out.write("\treturn page;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document)\r\n");
      out.write(".on('click', '.show', function(){\r\n");
      out.write("\t$('#map, #popup-background').css('display', 'block');\r\n");
      out.write("\r\n");
      out.write("\tvar xy = { lat: Number($(this).data('y')), lng: Number($(this).data('x')) };\r\n");
      out.write("\tvar id = new google.maps.Map(document.getElementById(\"map\"), {\r\n");
      out.write("\t    center: xy,\r\n");
      out.write("\t    zoom: 15,\r\n");
      out.write("  \t});\r\n");
      out.write("\r\n");
      out.write("\t//약국의 위치를 알수 있도록 마커를 표현\r\n");
      out.write("// \tnew google.maps.Marker({\r\n");
      out.write("// \t\tmap: id,   position: xy, title: $(this).text(),\r\n");
      out.write("// \t});\r\n");
      out.write("\r\n");
      out.write("\tvar info = new google.maps.InfoWindow();\t\r\n");
      out.write("\tinfo.setOptions({\r\n");
      out.write("\t\tcontent: '<div class=\"marker\">'+ $(this).text() +'</div>'\r\n");
      out.write("\t});\r\n");
      out.write("\tinfo.open(id, new google.maps.Marker({\r\n");
      out.write("\t\tmap:id, position: xy\t\r\n");
      out.write("\t}));\r\n");
      out.write("\t\r\n");
      out.write("}).on('click', '#popup-background', function(){\r\n");
      out.write("\t$('#map, #popup-background').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("}).on('click', '.page_list a', function(){\r\n");
      out.write("\tif( $('.pharmacy').length>0 ) pharmacy_list( $(this).data('page') );\r\n");
      out.write("\telse if( $('.animal').length>0 ) animal_list( $(this).data('page') );\r\n");
      out.write("\r\n");
      out.write("}).on('change', '#pageList', function(){\r\n");
      out.write("\tpageList = $(this).val();\r\n");
      out.write("\tif( $('.pharmacy').length>0 ) pharmacy_list(1);\r\n");
      out.write("\telse if( $('.animal').length>0 ) animal_list(1); \r\n");
      out.write("\r\n");
      out.write("}).on('click', '.grid-view', function(){\r\n");
      out.write("\t//목록형태로 보여지고 있는 경우\r\n");
      out.write("\tif( viewType=='list' ){\r\n");
      out.write("\t\tviewType='grid';\r\n");
      out.write("\t\tif( $('.pharmacy').length>0 ) pharmacy_grid_data( $('.pharmacy tr'), false );\r\n");
      out.write("\t\telse if( $('.animal').length>0 ) animal_grid_data( $('.animal tr'), false ); \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}).on('click', '.list-view', function(){\r\n");
      out.write("\t//그리드형태로 보여지고 있는 경우\r\n");
      out.write("\tif( viewType=='grid' ){\r\n");
      out.write("\t\tviewType='list';        \r\n");
      out.write("\t\tif( $('.pharmacy').length>0 ) pharmacy_list_data( $('.pharmacy li'), false );\r\n");
      out.write("\t\telse if( $('.animal').length>0 ) animal_list_data( $('.animal li'), false );\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}).on('change', '#sido', function(){ //시도변경\r\n");
      out.write("\tanimal_list( 1 );\r\n");
      out.write("\tanimal_sigungu();\r\n");
      out.write("\t\r\n");
      out.write("}).on('change', '#upkind', function(){ //축종변경\r\n");
      out.write("\tanimal_list( 1 );\r\n");
      out.write("\t//축종에 따른 품종을 조회\r\n");
      out.write("\tanimal_kind();\r\n");
      out.write("\t\r\n");
      out.write("}).on('change', '#kind', function(){ //품종변경\r\n");
      out.write("\tanimal_list( 1 );\r\n");
      out.write("\t\r\n");
      out.write("}).on('change', '#sigungu', function(){ //시군구변경\r\n");
      out.write("\tanimal_list(1);\r\n");
      out.write("\tanimal_shelter();\r\n");
      out.write("\t\r\n");
      out.write("}).on('change', '#shelter', function(){ //보호소변경\r\n");
      out.write("\tanimal_list(1);\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//그리드 --> 목록형태로 변경\r\n");
      out.write("function pharmacy_list_data( data, type ){\r\n");
      out.write("\tvar tag = '<table class=\"pharmacy\">'\r\n");
      out.write("\t\t+ '<tr><th class=\"w-px200\">약국명</th>'\r\n");
      out.write("\t\t+ '<th class=\"w-px140\">전화번호</th><th>주소</th></tr>';\r\n");
      out.write("\t\t\r\n");
      out.write("\tif( type ){ //API요청\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\ttag += '<tr><td><a class=\"show\" data-x=\"'+ this.XPos +'\" data-y=\"'+ this.YPos +'\" >'+ this.yadmNm +'</a></td>'\r\n");
      out.write("\t\t\t\t+ '<td>'+ this.telno +'</td>'\r\n");
      out.write("\t\t\t\t+ '<td class=\"left\">'+ this.addr +'</td>'\r\n");
      out.write("\t\t\t\t+ '</tr>';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t}else{ //화면만 변경\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\tvar $a = $(this).find('.show');\r\n");
      out.write("\t\t\ttag += '<tr>'\r\n");
      out.write("\t\t\t\t+ '<td><a class=\"show\" '\r\n");
      out.write("\t\t\t\t\t+ 'data-x=\"'+ $a.data('x') +'\" data-y=\"'+ $a.data('y') +'\" >'\r\n");
      out.write("\t\t\t\t\t+ $(this).children('div:eq(0)').text() +'</a></td>'\r\n");
      out.write("\t\t\t\t+ '<td>'+ $(this).children('div:eq(1)').text() +'</td>'\r\n");
      out.write("\t\t\t\t+ '<td class=\"left\">'+ $(this).children('div:eq(2)').text() +'</td>'\r\n");
      out.write("\t\t\t\t+ '</tr>';\r\n");
      out.write("\t\t});\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\ttag += '</table>';\r\n");
      out.write("\t$('#data-list').html( tag );\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var viewType = 'list';\r\n");
      out.write("\r\n");
      out.write("//목록 --> 그리드형태로 변경\r\n");
      out.write("function pharmacy_grid_data( data, type ){\r\n");
      out.write("\tvar tag = '<ul class=\"pharmacy grid\">';\r\n");
      out.write("\tif( type ){\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\ttag += '<li><div><a class=\"show\" '\r\n");
      out.write("\t\t\t\t+ 'data-x=\"'+ this.XPos +'\" data-y=\"'+ this.YPos +'\" >'\r\n");
      out.write("\t\t\t\t+ this.yadmNm +'</a></div>'\r\n");
      out.write("\t\t\t+ '<div>'+ this.telno +'</div>'\r\n");
      out.write("\t\t\t+ '<div>'+ this.addr +'</div>'\r\n");
      out.write("\t\t\t+ '</li>';\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdata.each(function(){\r\n");
      out.write("\t\t\tif( $(this).index()>0 ){\r\n");
      out.write("\t\t\t\tvar $a = $(this).find('.show');\t\r\n");
      out.write("\t\t\t\ttag += '<li><div><a class=\"show\" '\r\n");
      out.write("\t\t\t\t\t\t+ 'data-x=\"'+ $a.data('x') +'\" data-y=\"'+ $a.data('y') +'\" >'\r\n");
      out.write("\t\t\t\t\t\t+ $(this).children('td:eq(0)').text() +'</a></div>'\r\n");
      out.write("\t\t\t\t\t+ '<div>'+ $(this).children('td:eq(1)').text() +'</div>'\r\n");
      out.write("\t\t\t\t\t+ '<div>'+ $(this).children('td:eq(2)').text() +'</div>'\r\n");
      out.write("\t\t\t\t\t+ '</li>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\ttag += '</ul>';\r\n");
      out.write("\t$('#data-list').html(tag);\r\n");
      out.write("\tvar len = $('.pharmacy li').length;\r\n");
      out.write("\t$('#data-list .pharmacy').css('height'\r\n");
      out.write("\t\t\t, ((len%5>0 ? 1 :0) + Math.floor(len/5)) \r\n");
      out.write("\t\t\t\t\t* $('.pharmacy li').outerHeight(true) - 20 );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('.dataOption a').click(function(){\r\n");
      out.write("\t$('.dataOption a').removeClass();\r\n");
      out.write("\t$('.dataOption a').addClass('btn-empty');\r\n");
      out.write("\t$(this).removeClass('btn-empty').addClass('btn-fill');\r\n");
      out.write("\tvar idx = $(this).index();\r\n");
      out.write("\tif( idx==0 ) pharmacy_list(1);\r\n");
      out.write("\telse animal_list( 1 );\r\n");
      out.write("\t\r\n");
      out.write("// \tif( $(this).hasClass('btn-empty') ){\r\n");
      out.write("// \t\t$('.dataOption a').removeClass();\r\n");
      out.write("// \t\t$(this).addClass('btn-fill');\r\n");
      out.write("// \t\tvar idx = $(this).index();\r\n");
      out.write("// \t\t$('.dataOption a:not(:eq('+ idx +'))').addClass('btn-empty');\r\n");
      out.write("// \t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
